server:
  port: 8093
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my-service-group
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cebbank.service1.entity