server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
         - id: service1
           uri: lb://service1
           predicates:
            - Path=/service1/resource/**
         - id: service2
           uri: lb://service2
           predicates:
            - Path=/service2/resource/**
management:
  endpoints:
    web:
      exposure:
        include: '*'